# Generated by Django 4.2.30 on 2026-04-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_last_used_totp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_used_totp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
