# Generated by Django 4.2.30 on 2026-04-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_last_used_totp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_used_totp',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('CONNECTION_REQUEST', 'Connection Request'), ('CONNECTION_ACCEPTED', 'Connection Accepted'), ('NEW_POST', 'New Post from Connection'), ('COMPANY_ASSIGNED', 'Added as Company Recruiter')], max_length=30),
        ),
    ]
