# Generated by Django 4.2.29 on 2026-03-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_resume_digital_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumekey',
            name='key',
            field=models.CharField(help_text='Fernet symmetric key — in production this should be wrapped with an admin public key', max_length=200),
        ),
    ]
