# Generated by Django 4.2.30 on 2026-04-10 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_company_job_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='companies_employed_at', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resumekey',
            name='key',
            field=models.CharField(help_text='Fernet symmetric key', max_length=200),
        ),
    ]
